# Generated by Django 3.0.7 on 2021-05-11 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='user/default.jpg', upload_to='user/profile_pics')),
                ('date_of_birth', models.DateField(null=True, verbose_name='Birth Date')),
                ('gender', models.CharField(blank=True, max_length=16)),
                ('mobile', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=95, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
