# Generated by Django 2.2.10 on 2021-06-05 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalStuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docter_name', models.CharField(blank=True, max_length=16)),
                ('regural_beds', models.IntegerField(max_length=10000)),
                ('OCCUPIED_regural_beds', models.IntegerField(max_length=10000)),
                ('oxygen_beds', models.IntegerField(max_length=10000)),
                ('OCCUPIED_oxygen_beds', models.IntegerField(max_length=10000)),
                ('icu_beds', models.IntegerField(max_length=10000)),
                ('OCCUPIED_icu_beds', models.IntegerField(max_length=10000)),
                ('covid_lab', models.BooleanField(default=False)),
                ('verify', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_join', models.DateField(null=True, verbose_name='Birth Date')),
                ('hospital_name', models.CharField(blank=True, max_length=16)),
                ('mobile', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=95, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
